#!/usr/bin/env bash
# This script runs infinitely
echo $$ > "/var/run/holbertonscript.pid"
while :
do
	trap 'echo "I hate the kill command" && rm -f "/var/run/holbertonscript.pid" && kill -9 $$' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'rm -f "/var/run/holbertonscript.pid" && kill -9 $$' SIGQUIT
	echo "To infinity and beyond"
	sleep 2
done
