#!/usr/bin/env bash
# This script will print the clock
minutes="0"
hours="0"
while [ $hours -le 12 ] || [ $minutes -ne 0 ]
do
	if [ $minutes -eq 0 ]
	then
		echo "Hours: $hours"
		(( hours++ ))
	else
		echo "$minutes"
	fi

	(( minutes++ ))

	if [ $minutes -eq 60 ]
	then
		minutes="0"
	fi
done
