#!/usr/bin/env bash
# Configure a server with NGINX and add a block of code for redirects
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chmod 777 /usr/share/nginx/html/index.html
echo "Holberton School" > /usr/share/nginx/html/index.html
sudo sed -i "38i\ \tlocation /redirect_me {\n\t\treturn 301;\n\t}\n" /etc/nginx/sites-enabled/default
sudo touch /usr/share/nginx/html/custom_404.html
sudo chmod 777 /usr/share/nginx/html/custom_404.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sudo sed -i "42i\ \terror_page 404 /custom_404.html;\n\tlocation /xyz {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t\treturn 404;\n\t}\n" /etc/nginx/sites-enabled/default
sudo service nginx restart
