#!/usr/bin/env bash
# Configure a server with NGINX and add a block of code for redirects
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chmod 777 /usr/share/nginx/html/index.html
echo "Holberton School" > /usr/share/nginx/html/index.html
sudo sed -i "38i\ \tlocation /redirect_me {\n\t\treturn 301;\n\t}\n" /etc/nginx/sites-enabled/default
sudo sed -i "42i\ \tlocation /xyz {\n\t\treturn 404 \"Ceci n'est pas une page\";\n\t}\n" /etc/nginx/sites-enabled/default
sudo service nginx restart
