#!/usr/bin/env bash
# Configure a server with NGINX and add a block of code for redirects
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chmod 777 /usr/share/nginx/html/index.html
echo "Holberton School" > /usr/share/nginx/html/index.html
sudo sed -i "38i\ \tlocation /redirect_me {\n\t\treturn 301;\n\t}\n" /etc/nginx/sites-enabled/default
sudo touch /usr/share/nginx/html/404.html
sudo chmod 777 /usr/share/nginx/html/404.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
change="#error_page 404"
new="error_page 404"
sudo sed -i "s/$change/$new/" /etc/nginx/sites-enabled/default
sudo service nginx restart
