#!/usr/bin/env bash
# Script that configures a web server
chown nginx:nginx /etc/nginx/nginx.conf
chmod 444 /etc/nginx/nginx.conf
killall apache2
sed -i "s/listen 80/listen 8080/" /etc/nginx/sites-enabled/default
sed -i "s/\[::\]:80/\[::\]:8080/" /etc/nginx/sites-enabled/default
sudo -u nginx nginx
